data:
  source: csv
  start: 2018-01-01
  universe_csv: data/universe/watchlist.csv
  csv_dir: data/csv
signals:
  rule: R2_momo_rsi
  params:
    sma_fast: 20
    sma_slow: 50
    lookback_high: 252
    obv_window: 10
    atr_window: 14
    atr_min_pct: 0.005
    atr_max_pct: 0.1
    avoid_spike_ret: 0.2
    rsi_window: 14
    rsi_buy: 52
risk:
  risk_per_trade_pct: 0.01
  atr_mult_stop: 2.5
  max_pos_value_pct: 0.08
scheduler:
  daily_run_hour_ist: 19
costs:
  tc_bps: 5         # round-trip transaction cost in basis points
turnover_policy:
  target_avg_turnover_per_rebalance: 0.25    # 25%
  target_p95_turnover: 0.45                   # 45%

