# nested
signals:
  use_crossover: false  # Close>SMA(fast) if false; SMA(fast)>SMA(slow) if true

# flat (also supported)
use_crossover: false

# portfolio defaults (used by portfolio CLI if flags omitted)
top_n: 5
rebal_freq: ME        # month-end
cost_bps: 10          # commissions/slippage in bps per rebalance trade
cash_buffer: 0.00

