# Week 4: portfolio-level risk knobs
target_vol_ann: 0.20      # 20% annualized volatility target
lookback_days: 20         # rolling window (trading days)
min_mult: 0.50            # never scale below 0.5x
max_mult: 1.50            # never scale above 1.5x

# Drawdown throttle (based on equity curve)
dd_warn: 0.06             # 6% drawdown -> mild de-risk
dd_halt: 0.12             # 12% drawdown -> stronger de-risk

# Throttle mapping (applied to gross risk)
throttle_levels:
  warn: 0.75              # at dd_warn => 75% of normal risk
  halt: 0.50              # at dd_halt => 50% of normal risk