name: CI
on:
  push:
    branches: ["**"]       # run on any branch push
  pull_request:            # run for all PRs (any source → any target)
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - run: pip install -r requirements.txt
      - run: pip install ruff black pytest
      - run: ruff check .
      - run: ruff format --check .
      - run: black --check .
      - run: pytest -q
