name: CI

on:
  push:
    branches: ["**"]
  pull_request:

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Upgrade pip
        run: python -m pip install -U pip

      - name: Install project deps
        run: |
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          if [ -f requirements-dev.txt ]; then pip install -r requirements-dev.txt; fi
          pip install -e .

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-${{ hashFiles('.pre-commit-config.yaml') }}
          restore-keys: |
            pre-commit-${{ runner.os }}-

      - name: Run pre-commit (ruff, black, detect-secrets)
        run: pre-commit run --all-files

      - name: Quick import sanity
        run: python -c "import trading_stack_py, sys; print('pkg:', trading_stack_py.__file__)"

      - name: Run tests
        env:
          PYTHONPATH: ${{ github.workspace }}/src
        run: pytest -q

  cli-smoke-windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install project
        shell: pwsh
        run: |
          python -m pip install -U pip
          pip install -e .

      - name: Single-symbol CLI (synthetic)
        shell: pwsh
        run: |
          trading-stack --ticker RELIANCE.NS --start 2015-01-01 --source synthetic

      - name: Portfolio CLI (synthetic)
        shell: pwsh
        run: |
          trading-stack-portfolio --tickers RELIANCE.NS,HDFCBANK.NS,INFY.NS,ICICIBANK.NS,TCS.NS `
            --start 2018-01-01 --source synthetic --lookback 126 --top_n 3 --cost_bps 10
